---
title: "HW2"
author: "Hr2270"
date: "9/24/2020"
output: github_document
---

```{r setup}
library (tidyverse)
library (readxl)

```



## problem 1

Read mr trashwheel dataset

```{r load trash file}
trash_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19 (1).xlsx",
  sheet = 1,
  skip = 1,
  range = cell_cols("A:N")) %>%
  janitor::clean_names () %>%
  drop_na(dumpster) %>%  ## looks for missing values in this column only
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )

trash_df %>% view
````

read in precipitation data for 2017 and 2018

``` {r load precipitation}
precip_2018 =
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19 (1).xlsx",
             sheet = "2018 Precipitation",
             skip = 1
             ) %>%
  janitor::clean_names () %>%
  drop_na(month) %>%
  mutate(year = 2018) %>%
  relocate (year)

precip_2017 =
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19 (1).xlsx",
             sheet = "2017 Precipitation",
             skip = 1
             ) %>%
  janitor::clean_names () %>%
  drop_na(month) %>%
  mutate(year = 2017) %>%
  relocate (year)

```

Now combine anual precipitation
```{r combine precip}
precip_df = 
  bind_rows (precip_2018, precip_2017) %>%
  mutate(month = month.name[month]) ##square brackets to mutate the vector
```

##Problem 2

```{read NYC transit file}
transit_df =
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names () %>%
  select (line, station_name, station_latitude, station_longitude, contains(c("route")), entry, vending, entrance_type, ada) %>%
  mutate(entry = ifelse(entry == "YES", 1, 0),
         entry = as.logical(entry)) %>%
  mutate(route8 = as.character(route8), 
        route9 = as.character(route9), 
        route10 = as.character(route10),
        route11 = as.character(route11)) %>%
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name",
  )

nrow(distinct(transit_df))

transit_df_A = transit_df %>%
filter(route_name == "A")

nrow(distinct(transit_df_A, station_name))
nrow(distinct(transit_df_A, station_name, ada == TRUE))

?nrow


```
